<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <JellyfinTargetFramework Condition="'$(JellyfinTargetFramework)' == ''">net9.0</JellyfinTargetFramework>
    <TargetFramework>$(JellyfinTargetFramework)</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.QualityBitrateManager</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <ImplicitUsings>enable</ImplicitUsings>
    <PluginVersion Condition="'$(PluginVersion)' == ''">1.0.0.1</PluginVersion>
    <Version>$(PluginVersion)</Version>
    <AssemblyVersion>$(PluginVersion)</AssemblyVersion>
    <FileVersion>$(PluginVersion)</FileVersion>
    <JellyfinVersion Condition="'$(JellyfinVersion)' == ''">10.11.0</JellyfinVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinVersion)"><ExcludeAssets>runtime</ExcludeAssets></PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="$(JellyfinVersion)"><ExcludeAssets>runtime</ExcludeAssets></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Remove="Configuration/config.html" />
    <EmbeddedResource Include="Configuration/config.html" />
  </ItemGroup>
</Project>
